Repository ott-jax/ott, pull requests merged in 2022-07, with the labels that each got.

#93 Fix/point cloud apply cost fn
  ott/core/layers.py
  ott/core/quad_problems.py
  ott/geometry/geometry.py
  ott/geometry/low_rank.py
  ott/geometry/pointcloud.py
  tests/geometry/geometry_lr_test.py
Labels: bug, enhancement

#96 Feature/lr gw apply output
  ott/core/gromov_wasserstein.py
  ott/core/sinkhorn_lr.py
  tests/core/fused_gromov_wasserstein_test.py
  tests/core/gromov_wasserstein_test.py
Labels: enhancement

#101 Feature/fast tests
  .codecov.yml
  .github/workflows/tests.yml
  CONTRIBUTING.md
  README.md
  ott/tools/sinkhorn_divergence.py
  setup.cfg
  tests/conftest.py
  tests/core/continuous_barycenter_test.py
  tests/core/discrete_barycenter_test.py
  tests/core/fused_gromov_wasserstein_test.py
  tests/core/gromov_wasserstein_test.py
  tests/core/gromov_wasserstein_unbalanced_test.py
  tests/core/icnn_test.py
  tests/core/neuraldual_test.py
  tests/core/sinkhorn_anderson_acceleration_test.py
  tests/core/sinkhorn_bures_test.py
  tests/core/sinkhorn_diff_grid_loc_test.py
  tests/core/sinkhorn_diff_grid_weights_test.py
  tests/core/sinkhorn_diff_precond_test.py
  tests/core/sinkhorn_diff_test.py
  tests/core/sinkhorn_extra_test.py
  tests/core/sinkhorn_grid_test.py
  tests/core/sinkhorn_hessian_test.py
  tests/core/sinkhorn_implicit_lse_test.py
  tests/core/sinkhorn_implicit_test.py
  tests/core/sinkhorn_jacobian_apply_test.py
  tests/core/sinkhorn_jit_test.py
  tests/core/sinkhorn_lr_test.py
  tests/core/sinkhorn_online_large_test.py
  tests/core/sinkhorn_potentials_jacobian_test.py
  tests/core/sinkhorn_test.py
  tests/core/sinkhorn_unbalanced_test.py
  tests/geometry/geometry_costs_test.py
  tests/geometry/geometry_lr_test.py
  tests/geometry/geometry_lse_test.py
  tests/geometry/geometry_pointcloud_apply_test.py
  tests/geometry/geometry_pointcloud_generalcost_test.py
  tests/geometry/matrix_square_root_test.py
  tests/geometry/scaling_cost_test.py
  tests/tools/gaussian_mixture/fit_gmm_pair_test.py
  tests/tools/gaussian_mixture/fit_gmm_test.py
  tests/tools/gaussian_mixture/gaussian_mixture_pair_test.py
  tests/tools/gaussian_mixture/gaussian_mixture_test.py
  tests/tools/gaussian_mixture/gaussian_test.py
  tests/tools/gaussian_mixture/linalg_test.py
  tests/tools/gaussian_mixture/probabilities_test.py
  tests/tools/gaussian_mixture/scale_tril_test.py
  tests/tools/sinkhorn_divergence_differentiability_test.py
  tests/tools/sinkhorn_divergence_test.py
  tests/tools/soft_sort_test.py
  tests/tools/transport_test.py
Labels: enhancement

#103 Fix/axis norm
  ott/geometry/pointcloud.py
  tests/geometry/geometry_pointcloud_apply_test.py
Labels: bug

#99 Generic LR cost decomposition
  .github/workflows/tests.yml
  docs/conf.py
  docs/core.rst
  docs/index.rst
  docs/notebooks/GWLRSinkhorn.ipynb
  docs/notebooks/LRSinkhorn.ipynb
  docs/references.bib
  docs/references.rst
  ott/core/gromov_wasserstein.py
  ott/core/sinkhorn_lr.py
  ott/core/was_solver.py
  ott/geometry/geometry.py
  ott/geometry/grid.py
  ott/geometry/low_rank.py
  ott/geometry/pointcloud.py
  setup.cfg
  tests/core/continuous_barycenter_test.py
  tests/core/fused_gromov_wasserstein_test.py
  tests/geometry/geometry_lr_test.py
  tests/geometry/geometry_subset_test.py
Labels: enhancement

#89 demo and fixes for barycenters of GMMs
  docs/index.rst
  docs/notebooks/wasserstein_barycenters_gmms.ipynb
  ott/core/bar_problems.py
  ott/core/segment.py
  ott/geometry/costs.py
  ott/tools/gaussian_mixture/gaussian.py
  ott/tools/gaussian_mixture/gaussian_mixture.py
  ott/tools/sinkhorn_divergence.py
  tests/core/continuous_barycenter_test.py
  tests/tools/gaussian_mixture/gaussian_mixture_test.py
  tests/tools/sinkhorn_divergence_test.py
Labels: enhancement

#87 Add (F)GW barycenters
  docs/conf.py
  docs/core.rst
  docs/index.rst
  docs/references.bib
  ott/core/__init__.py
  ott/core/bar_problems.py
  ott/core/continuous_barycenter.py
  ott/core/gromov_wasserstein.py
  ott/core/gw_barycenter.py
  ott/core/segment.py
  ott/core/was_solver.py
Labels: enhancement

#109 [ci skip] Fix duplicate bibtex entry and a typo
  docs/references.bib
Labels: bug, documentation

#113 GW different cost ranks
  ott/core/gromov_wasserstein.py
  ott/core/linear_problems.py
  ott/core/quad_problems.py
  ott/core/segment.py
  ott/geometry/geometry.py
  ott/geometry/pointcloud.py
  tests/core/fused_gromov_wasserstein_test.py
  tests/core/gromov_wasserstein_test.py
Labels: enhancement
