Repository ott-jax/ott, pull requests merged in 2023-03, with the labels that each got.

#325 Remove ignoring passed params in ICNN
  src/ott/solvers/nn/models.py
Labels: bug

#280 Parameter to make line strength proportional to coupling strength in Plot
  src/ott/tools/plot.py
Labels: hackathon

#329 Remove sparse option in `Graph` geometry
  .github/workflows/tests.yml
  docs/conf.py
  docs/math.rst
  docs/references.bib
  pyproject.toml
  src/ott/geometry/graph.py
  src/ott/math/__init__.py
  src/ott/math/decomposition.py
  tests/geometry/graph_test.py
Labels: bug

#331 gh: refactor community files
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
Labels: misc

#334 Docs/fix minor issues
  docs/geometry.rst
  docs/index.rst
  docs/initializers/index.rst
  docs/initializers/linear.rst
  docs/initializers/nn.rst
  docs/initializers/quadratic.rst
  docs/problems/index.rst
  docs/problems/linear.rst
  docs/problems/nn.rst
  docs/problems/quadratic.rst
  docs/solvers/index.rst
  docs/solvers/linear.rst
  docs/solvers/nn.rst
  docs/solvers/quadratic.rst
  docs/tools.rst
  docs/utils.rst
  pyproject.toml
Labels: documentation

#335 Fix/jit inside jit
  docs/conf.py
  docs/index.rst
  docs/tutorials/notebooks/basic_ot_between_datasets.ipynb
  src/ott/solvers/linear/continuous_barycenter.py
  src/ott/solvers/linear/sinkhorn.py
  src/ott/solvers/linear/sinkhorn_lr.py
  src/ott/solvers/quadratic/gromov_wasserstein.py
  src/ott/solvers/quadratic/gw_barycenter.py
  src/ott/solvers/was_solver.py
  tests/geometry/graph_test.py
  tests/solvers/linear/sinkhorn_diff_test.py
  tests/solvers/linear/sinkhorn_test.py
Labels: bug, deprecation

#340 Remove assertions in cost functions
  docs/tutorials/notebooks/basic_ot_between_datasets.ipynb
  src/ott/geometry/costs.py
Labels: enhancement

#348 Feature/unscaled gw cost
  docs/spelling/technical.txt
  docs/tutorials/notebooks/sinkhorn_divergence_gradient_flow.ipynb
  pyproject.toml
  src/ott/geometry/geometry.py
  src/ott/initializers/linear/initializers_lr.py
  src/ott/initializers/quadratic/initializers.py
  src/ott/problems/quadratic/quadratic_problem.py
  src/ott/solvers/quadratic/gromov_wasserstein.py
  tests/geometry/subsetting_test.py
  tests/solvers/quadratic/gw_test.py
Labels: enhancement
