Repository ott-jax/ott, pull requests merged in 2023-08, with the labels that each got.

#403 update nb
  .github/workflows/tests.yml
  docs/tutorials/notebooks/MetaOT.ipynb
  docs/tutorials/notebooks/OTT_&_POT.ipynb
  docs/tutorials/notebooks/sparse_monge_displacements.ipynb
  pyproject.toml
  src/ott/geometry/costs.py
Labels: documentation

#404 Test `default_progress_fn`, skip `types.py`
  pyproject.toml
  src/ott/utils.py
  tests/solvers/linear/sinkhorn_test.py
Labels: misc

#413 Feature/better io callbacks
  docs/tutorials/notebooks/tracking_progress.ipynb
  docs/utils.rst
  pyproject.toml
  src/ott/solvers/linear/sinkhorn.py
  src/ott/solvers/linear/sinkhorn_lr.py
  src/ott/solvers/quadratic/gromov_wasserstein.py
  src/ott/utils.py
  tests/solvers/linear/sinkhorn_lr_test.py
  tests/solvers/linear/sinkhorn_test.py
Labels: enhancement

#412 Feature/optional dependencies
  .readthedocs.yaml
  docs/index.rst
  docs/spelling/misc.txt
  docs/spelling/technical.txt
  pyproject.toml
  src/ott/initializers/__init__.py
  src/ott/solvers/__init__.py
  src/ott/solvers/linear/sinkhorn.py
  src/ott/tools/__init__.py
  src/ott/tools/gaussian_mixture/fit_gmm_pair.py
  src/ott/tools/map_estimator.py
Labels: misc

#416 Update pre-commits
  .pre-commit-config.yaml
  LICENSE
  docs/spelling/technical.txt
  pyproject.toml
  src/ott/geometry/costs.py
  src/ott/initializers/linear/initializers_lr.py
  src/ott/solvers/linear/acceleration.py
  src/ott/solvers/linear/sinkhorn.py
  src/ott/tools/gaussian_mixture/scale_tril.py
  tests/solvers/linear/sinkhorn_test.py
Labels: misc
