Repository ott-jax/ott, pull requests merged in 2023-11, with the labels that each got.

#451 Added CDF distance to Univariate Solver
  src/ott/solvers/linear/univariate.py
  tests/solvers/linear/univariate_test.py
  tests/solvers/quadratic/lower_bound_test.py
Labels: enhancement

#459 Use PyPI trusted publishers
  .github/workflows/lint.yml
  .github/workflows/publish.yml
  .github/workflows/tests.yml
Labels: misc

#466 Restructure neural module
  docs/solvers/nn.rst
  src/ott/__init__.py
  src/ott/datasets.py
  src/ott/initializers/__init__.py
  src/ott/neural/__init__.py
  src/ott/neural/models/__init__.py
  src/ott/neural/models/conjugate_solvers.py
  src/ott/neural/models/layers.py
  src/ott/neural/models/models.py
  src/ott/neural/solvers/__init__.py
  src/ott/neural/solvers/losses.py
  src/ott/neural/solvers/map_estimator.py
  src/ott/neural/solvers/neuraldual.py
  src/ott/problems/__init__.py
  src/ott/solvers/__init__.py
  src/ott/solvers/nn/models.py
  src/ott/tools/__init__.py
  tests/neural/__init__.py
  tests/neural/icnn_test.py
  tests/neural/losses_test.py
  tests/neural/map_estimator_test.py
  tests/neural/meta_initializer_test.py
  tests/neural/neuraldual_test.py
Labels: enhancement

#475 Enable 3.12 CI
  .github/workflows/tests.yml
  pyproject.toml
Labels: misc

#474 Feature/apply lse mode
  docs/references.bib
  src/ott/geometry/geodesic.py
  src/ott/geometry/graph.py
  src/ott/solvers/linear/sinkhorn.py
  src/ott/types.py
  tests/geometry/geodesic_test.py
  tests/geometry/graph_test.py
Labels: enhancement

#473 Fix/neural docs
  docs/index.rst
  docs/initializers/index.rst
  docs/initializers/nn.rst
  docs/neural/index.rst
  docs/neural/solvers.rst
  docs/problems/index.rst
  docs/problems/nn.rst
  docs/solvers/index.rst
  docs/solvers/linear.rst
  docs/solvers/nn.rst
  docs/spelling/technical.txt
  docs/tools.rst
  src/ott/datasets.py
  src/ott/geometry/distrib_costs.py
  src/ott/neural/__init__.py
  src/ott/neural/layers.py
  src/ott/neural/losses.py
  src/ott/neural/models.py
  src/ott/neural/models/__init__.py
  src/ott/neural/solvers/__init__.py
  src/ott/neural/solvers/conjugate.py
  src/ott/neural/solvers/map_estimator.py
  src/ott/neural/solvers/neuraldual.py
  src/ott/solvers/linear/univariate.py
  src/ott/solvers/quadratic/lower_bound.py
  tests/neural/icnn_test.py
  tests/neural/losses_test.py
  tests/neural/map_estimator_test.py
  tests/neural/meta_initializer_test.py
  tests/neural/neuraldual_test.py
Labels: documentation
