Repository ott-jax/ott, pull requests merged in 2023-02, with the labels that each got.

#242 Add GPU test runner
  .editorconfig
  .github/workflows/tests.yml
  .pre-commit-config.yaml
  docs/geometry.rst
  docs/index.rst
  docs/initializers/index.rst
  docs/initializers/linear.rst
  docs/initializers/nn.rst
  docs/initializers/quadratic.rst
  docs/math.rst
  docs/problems/index.rst
  docs/problems/linear.rst
  docs/problems/quadratic.rst
  docs/solvers/index.rst
  docs/solvers/linear.rst
  docs/solvers/nn.rst
  docs/solvers/quadratic.rst
  docs/tools.rst
  pyproject.toml
  src/ott/geometry/geometry.py
  src/ott/problems/quadratic/quadratic_problem.py
  tests/initializers/quadratic/gw_init_test.py
  tests/math/matrix_square_root_test.py
  tests/solvers/linear/continuous_barycenter_test.py
  tests/solvers/linear/sinkhorn_test.py
  tests/solvers/nn/icnn_test.py
  tests/tools/gaussian_mixture/fit_gmm_pair_test.py
  tests/tools/k_means_test.py
Labels: misc

#247 Remove shape check in `LRCGeometry`
  .pre-commit-config.yaml
  src/ott/geometry/low_rank.py
  tests/geometry/low_rank_test.py
Labels: bugfix

#244 Add regularized costs
  .github/workflows/tests.yml
  docs/geometry.rst
  docs/index.rst
  docs/references.bib
  pyproject.toml
  src/ott/geometry/costs.py
  tests/geometry/costs_test.py
Labels: enhancement

#219 Improvements to the neural dual solver
  docs/conf.py
  docs/index.rst
  docs/problems/index.rst
  docs/problems/nn.rst
  docs/references.bib
  docs/solvers/nn.rst
  docs/tutorials/notebooks/icnn_inits.ipynb
  docs/tutorials/notebooks/neural_dual.ipynb
  pyproject.toml
  src/ott/problems/__init__.py
  src/ott/problems/linear/potentials.py
  src/ott/problems/nn/__init__.py
  src/ott/problems/nn/dataset.py
  src/ott/solvers/linear/sinkhorn.py
  src/ott/solvers/nn/__init__.py
  src/ott/solvers/nn/conjugate_solvers.py
  src/ott/solvers/nn/icnn.py
  src/ott/solvers/nn/models.py
  src/ott/solvers/nn/neuraldual.py
  tests/solvers/nn/icnn_test.py
  tests/solvers/nn/neuraldual_test.py
Labels: enhancement, bugfix

#270 fixed the docs about the implicit_diff argument
  src/ott/solvers/linear/sinkhorn.py
Labels: hackathon

#279 Add pre-commit CI cache
  .github/workflows/lint.yml
Labels: hackathon

#269 Fix flake8 `D10{1,2,3}` errors
  .flake8
  .gitignore
  src/ott/geometry/costs.py
  src/ott/geometry/epsilon_scheduler.py
  src/ott/geometry/geometry.py
  src/ott/geometry/graph.py
  src/ott/geometry/grid.py
  src/ott/geometry/low_rank.py
  src/ott/geometry/pointcloud.py
  src/ott/initializers/linear/initializers.py
  src/ott/initializers/linear/initializers_lr.py
  src/ott/initializers/nn/initializers.py
  src/ott/initializers/quadratic/initializers.py
  src/ott/math/decomposition.py
  src/ott/math/matrix_square_root.py
  src/ott/math/unbalanced_functions.py
  src/ott/math/utils.py
  src/ott/problems/linear/barycenter_problem.py
  src/ott/problems/linear/linear_problem.py
  src/ott/problems/linear/potentials.py
  src/ott/problems/nn/dataset.py
  src/ott/problems/quadratic/gw_barycenter.py
  src/ott/problems/quadratic/quadratic_costs.py
  src/ott/problems/quadratic/quadratic_problem.py
  src/ott/solvers/linear/acceleration.py
  src/ott/solvers/linear/continuous_barycenter.py
  src/ott/solvers/linear/discrete_barycenter.py
  src/ott/solvers/linear/sinkhorn.py
  src/ott/solvers/linear/sinkhorn_lr.py
  src/ott/solvers/nn/conjugate_solvers.py
  src/ott/solvers/nn/models.py
  src/ott/solvers/nn/neuraldual.py
  src/ott/solvers/quadratic/gromov_wasserstein.py
  src/ott/solvers/quadratic/gw_barycenter.py
  src/ott/solvers/was_solver.py
  src/ott/tools/gaussian_mixture/gaussian.py
  src/ott/tools/gaussian_mixture/gaussian_mixture.py
  src/ott/tools/gaussian_mixture/gaussian_mixture_pair.py
  src/ott/tools/gaussian_mixture/probabilities.py
  src/ott/tools/gaussian_mixture/scale_tril.py
  src/ott/tools/sinkhorn_divergence.py
  src/ott/utils.py
Labels: hackathon

#288 Added CostFn and Plot to the documentation
  docs/geometry.rst
  docs/tools.rst
Labels: hackathon

#286 add `primal_cost` property to output of GW, to compute cost without any regularization.
  docs/references.bib
  src/ott/problems/quadratic/quadratic_problem.py
  src/ott/solvers/linear/sinkhorn.py
  src/ott/solvers/linear/sinkhorn_lr.py
  src/ott/solvers/quadratic/gromov_wasserstein.py
  tests/solvers/quadratic/gw_test.py
Labels: hackathon

#278 add `ruff` and remove redundant pre-commits
  .pre-commit-config.yaml
  examples/fairness/losses.py
  examples/fairness/main.py
  examples/fairness/train.py
  examples/soft_error/data.py
  examples/soft_error/losses.py
  examples/soft_error/main.py
  examples/soft_error/train.py
  pyproject.toml
  src/ott/geometry/__init__.py
  src/ott/problems/linear/potentials.py
  src/ott/solvers/linear/sinkhorn_lr.py
  src/ott/solvers/nn/conjugate_solvers.py
  src/ott/solvers/nn/neuraldual.py
  src/ott/tools/gaussian_mixture/fit_gmm_pair.py
  src/ott/tools/gaussian_mixture/gaussian_mixture.py
  src/ott/tools/plot.py
Labels: hackathon

#310 Fix/epsilon regularization
  src/ott/geometry/epsilon_scheduler.py
  src/ott/geometry/geometry.py
  src/ott/geometry/graph.py
  src/ott/geometry/grid.py
  src/ott/geometry/low_rank.py
  src/ott/geometry/pointcloud.py
  src/ott/problems/quadratic/quadratic_problem.py
  tests/geometry/graph_test.py
  tests/solvers/linear/sinkhorn_test.py
Labels: bugfix

#311 Fix small TODOs
  MANIFEST.in
  README.md
  docs/_static/images/couplings.png
  docs/tutorials/notebooks/soft_sort.ipynb
  src/ott/geometry/epsilon_scheduler.py
  src/ott/geometry/geometry.py
  src/ott/geometry/grid.py
  src/ott/geometry/low_rank.py
  src/ott/geometry/pointcloud.py
  tests/geometry/low_rank_test.py
  tests/geometry/subsetting_test.py
Labels: documentation

#313 Add CI tests for upstream JAX
  .github/workflows/tests.yml
  CONTRIBUTING.md
  pyproject.toml
Labels: misc

#309 Subsample initializer
  docs/initializers/linear.rst
  src/ott/initializers/linear/initializers.py
  src/ott/initializers/nn/initializers.py
  src/ott/solvers/linear/sinkhorn.py
  tests/initializers/linear/sinkhorn_init_test.py
Labels: enhancement

#228 feat: add progress reporting to Sinkhorn
  docs/index.rst
  docs/solvers/linear.rst
  docs/utils.rst
  src/ott/solvers/linear/sinkhorn.py
  src/ott/utils.py
  tests/solvers/linear/sinkhorn_test.py
Labels: enhancement, hackathon

#290 Make random seeding consistent with PRNG keys everywhere instead of seeds
  src/ott/geometry/geometry.py
  src/ott/geometry/low_rank.py
  src/ott/initializers/linear/initializers_lr.py
  src/ott/problems/nn/dataset.py
  src/ott/problems/quadratic/quadratic_problem.py
  src/ott/solvers/linear/continuous_barycenter.py
  src/ott/solvers/linear/sinkhorn_lr.py
  src/ott/solvers/nn/models.py
  src/ott/solvers/nn/neuraldual.py
  src/ott/solvers/quadratic/gromov_wasserstein.py
  src/ott/solvers/quadratic/gw_barycenter.py
  src/ott/tools/gaussian_mixture/fit_gmm.py
  src/ott/tools/gaussian_mixture/gaussian.py
  src/ott/tools/gaussian_mixture/gaussian_mixture.py
  src/ott/tools/gaussian_mixture/linalg.py
  src/ott/tools/gaussian_mixture/probabilities.py
  src/ott/tools/gaussian_mixture/scale_tril.py
  src/ott/tools/k_means.py
  tests/geometry/costs_test.py
  tests/geometry/graph_test.py
  tests/geometry/low_rank_test.py
  tests/geometry/pointcloud_test.py
  tests/geometry/scaling_cost_test.py
  tests/geometry/subsetting_test.py
  tests/initializers/linear/sinkhorn_init_test.py
  tests/initializers/linear/sinkhorn_lr_init_test.py
  tests/initializers/quadratic/gw_init_test.py
  tests/math/lse_test.py
  tests/math/matrix_square_root_test.py
  tests/problems/linear/potentials_test.py
  tests/solvers/linear/continuous_barycenter_test.py
  tests/solvers/linear/sinkhorn_diff_test.py
  tests/solvers/linear/sinkhorn_grid_test.py
  tests/solvers/linear/sinkhorn_lr_test.py
  tests/solvers/linear/sinkhorn_misc_test.py
  tests/solvers/linear/sinkhorn_test.py
  tests/solvers/nn/icnn_test.py
  tests/solvers/quadratic/fgw_test.py
  tests/solvers/quadratic/gw_barycenter_test.py
  tests/solvers/quadratic/gw_test.py
  tests/tools/gaussian_mixture/fit_gmm_pair_test.py
  tests/tools/gaussian_mixture/fit_gmm_test.py
  tests/tools/gaussian_mixture/gaussian_mixture_pair_test.py
  tests/tools/gaussian_mixture/gaussian_mixture_test.py
  tests/tools/gaussian_mixture/gaussian_test.py
  tests/tools/gaussian_mixture/linalg_test.py
  tests/tools/gaussian_mixture/probabilities_test.py
  tests/tools/gaussian_mixture/scale_tril_test.py
  tests/tools/k_means_test.py
  tests/tools/segment_sinkhorn_test.py
  tests/tools/sinkhorn_divergence_test.py
  tests/tools/soft_sort_test.py
Labels: hackathon

#318 Add `Soft-DTW` cost function
  .pre-commit-config.yaml
  docs/geometry.rst
  docs/references.bib
  pyproject.toml
  src/ott/geometry/costs.py
  src/ott/math/utils.py
  tests/geometry/costs_test.py
  tests/geometry/graph_test.py
Labels: enhancement

#321 Fix/sinkdiv hessian
  docs/tutorials/notebooks/Hessians.ipynb
  src/ott/solvers/linear/implicit_differentiation.py
  src/ott/tools/sinkhorn_divergence.py
Labels: bug
