Repository ott-jax/ott, pull requests merged in 2024-08, with the labels that each got.

#567 Feature/progot
  docs/references.bib
  docs/tools.rst
  docs/tutorials/linear/700_progot.ipynb
  src/ott/tools/__init__.py
  src/ott/tools/progot.py
Labels: enhancement

#569 Fix/univariate non ti
  src/ott/solvers/linear/univariate.py
  tests/solvers/linear/univariate_test.py
Labels: bug

#568 sink div for LR
  docs/references.bib
  docs/tutorials/linear/300_LRSinkhorn.ipynb
  src/ott/math/utils.py
  src/ott/solvers/linear/sinkhorn_lr.py
  src/ott/tools/progot.py
  src/ott/tools/sinkhorn_divergence.py
  tests/tools/sinkhorn_divergence_test.py
Labels: enhancement

#291 Add tutorial for unbalanced OT
  docs/references.bib
  docs/tutorials/linear/800_Unbalanced_OT.ipynb
Labels: hackathon

#570 Edits to ProgOT
  docs/tutorials/linear/700_progot.ipynb
  src/ott/tools/progot.py
Labels: documentation

#571 Feature/update progot
  docs/tutorials/linear/700_progot.ipynb
  src/ott/tools/progot.py
Labels: misc
