Repository ott-jax/ott, pull requests merged in 2024-11, with the labels that each got.

#594 add glossary
  docs/glossary.rst
  docs/index.rst
  docs/math.rst
  docs/spelling/technical.txt
  pyproject.toml
  src/ott/neural/methods/expectile_neural_dual.py
  src/ott/neural/methods/monge_gap.py
  src/ott/solvers/linear/implicit_differentiation.py
  src/ott/solvers/linear/sinkhorn.py
  src/ott/solvers/quadratic/gromov_wasserstein.py
  tests/solvers/linear/sinkhorn_diff_test.py
Labels: documentation

#598 add Hungarian solver from optax
  docs/geometry.rst
  docs/glossary.rst
  docs/spelling/technical.txt
  docs/tools.rst
  pyproject.toml
  src/ott/geometry/costs.py
  src/ott/geometry/geometry.py
  src/ott/math/utils.py
  src/ott/tools/__init__.py
  src/ott/tools/unreg.py
  tests/tools/unreg_test.py
Labels: enhancement

#600 Fix Wrong implementation of u_t(x|z) in Brownian Bridge
  src/ott/neural/methods/flows/dynamics.py
  src/ott/neural/methods/flows/genot.py
  src/ott/neural/methods/flows/otfm.py
Labels: bug

#601 Fix CI
  .github/workflows/tests.yml
  pyproject.toml
Labels: misc
